import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import { useState } from 'react'

export default function Home() {
  const [checkbox, setCheckbox] = useState(false)

  const toggleCheckbox = () => {
    setCheckbox(!checkbox)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <h1 className='logo'>Logo</h1>

          <div className={checkbox ? 'checkbox-checked' : 'checkbox'} onClick={toggleCheckbox}>
            <span></span>
            <span></span>
            <span></span>
          </div>
          
          <nav className={checkbox && 'nav-checked'}>
            <p>Home</p>
            <p>Skills</p>
            <p>Home</p>
            <p>Contact</p>
          </nav>
        </header>

        <section>
          Hello
        </section>

        <section>
          Hello
        </section>
        
        <section>
          Hello
        </section>
      </main>
    </>
  )
}
